apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: staged-workflow
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: This is a system-generated parameter and is required for use in
          application releases. Refer to
          https://docs.cloudbees.com/docs/cloudbees-platform/latest/applications/releases#manifest
          for the expected format
metadata:
  stages/v1alpha1:
    - name: PREPROD
      jobs:
        - PREPROD
    - name: Production
      jobs:
        - Production
jobs:
  PREPROD:
    environment: PREPROD
    uses: ./.cloudbees/workflows/deployer.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: ${{ cloudbees.job.environment }}
  Production:
    needs:
      - PREPROD
    environment: Production
    uses: ./.cloudbees/workflows/deployer.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: ${{ cloudbees.job.environment }}
